### PR TITLE
Documentation and DockerFile

### PR DESCRIPTION
**Pull request by TheJSGirl**
- Added documentation
- Dockerized App

### CODE REVIEW

**Comment by ashokdey** [comment]
Thanks, @TheJSGirl this seems a good update. Just add a screenshot to verify that the docker container is running fine.

**Comment by TheJSGirl** [comment]
> Thanks, @TheJSGirl this seems a good update. Just add a screenshot to verify that the docker container is running fine.

Yeah, working on it. I was stuck with cleaning a few commits.

**Comment by ashokdey** [comment]
@TheJSGirl, I see you are going good but now you broke the tests. Please revert back the DB URL so as to pass the test cases.

You can move the example URL in the README file

Thanks!

**Comment by ashokdey** [comment]
@TheJSGirl tests are hanging, I see you updated the `Mocha` package. Read more here: https://stackoverflow.com/questions/50372866/mocha-not-exiting-after-test

And please take care of this from next time.

**Comment by harpreetkhalsagtbit** [comment]
@ashokdey In comments here, I can see Teaching, Guiding, Correcting mistakes, Appreciation and a nice welcome to the new contributors. Great.

**Comment by ashokdey** [comment]
Hey @harpreetkhalsagtbit, I am glad that you liked it. DM me on **[Twitter](https://twitter.com/ashokdey_)** if you need any assistance for the same coming month.

**Pull request merged**
